### ISSUE TITLE
Failed to activate the cut-line package

### ISSUE THREAD

**Issue by yuzhigang33** [tekkub/cut-line#26]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [cut-line](https://github.com/tekkub/cut-line) package, v0.10.0
### Stack Trace

Failed to activate the cut-line package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/yzg/.atom/packages/cut-line/lib/cut-line.coffee:4:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:302:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git"
    ],
    "disabledPackages": [
      "autocomplete"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
autocomplete-plus, v2.9.0
cut-line, v0.10.0
highlight-selected, v0.9.1
html2jade, v0.7.0
language-jade, v0.3.0

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
I did a fork and updated the package, and released it under the name [cut-line-2](https://github.com/tcarlsen/atom-cut-line-2)

**Comment by deiga** [comment]
@tcarlsen And then you removed it? Why not submit a PR?

**Comment by tcarlsen** [comment]
Yeah I removed it. Atom core now supports this behavior, so you don't need a package like this anymore
